### ISSUE TITLE
Download mods from workshop

### ISSUE THREAD

**Issue by luca-ha** [muttleyxd/arma3-unix-launcher#30]
Hi !
I really like your launcher, but even though I subscribed to mods on the Arma 3 workshop, they don't appear in the launcher (see picture for an example).
![subscribed_mod](https://user-images.githubusercontent.com/43295692/50703377-2bd22380-1054-11e9-8673-c1f55672a0fb.png)
![arma_launcher](https://user-images.githubusercontent.com/43295692/50703409-4c01e280-1054-11e9-97a6-55642a77e9da.png)

I really don't know what I should do, am I doing something wrong ? Or is your launcher not intended to do that ?

Best regards

**Comment by muttleyxd** [comment]
@luca-ha

Does the launcher ask you to select Steam install path?
Also I'd like to know what distro are you on (there were some issues with Kubuntu, some time ago)

Would you give me output arma3-unix-launcher creates?
You would need to open up the terminal and run

```
arma3-unix-launcher --purge
arma3-unix-launcher --verbose >launcher.log
```

and then paste here content of launcher.log file after it launches and then you can close it.

**Comment by luca-ha** [comment]
Thank's for the quick reply.
I'm on Ubuntu 18.04. I don't think I've been asked to select Steam path. 
I've run the two commands you gave me, and I had to give the Steam install path. Now there are some mods, but still not all (RHSUSAF not for example). 
![launcher_with_some_mods](https://user-images.githubusercontent.com/43295692/50711080-3d73f500-106d-11e9-83c3-873f6b5f8bac.png)
Here's the log file: 
[launcher.log](https://github.com/muttleyxd/arma3-unix-launcher/files/2728545/launcher.log)

**Comment by muttleyxd** [comment]
Please check if this directory exists
`/media/lucah/Games/SteamLibrary/steamapps/workshop/content/107410/843577117`

To me it looks like Steam didn't download the mod for you, I'd try unsubscribing and subscribing again.
Also I've put some improvements on master, so please rebuild the launcher
```
git fetch origin
git pull
cd build
make
```

Also please purge before running new version, I've fixed these weird number-named mods (like 281074849), they won't appear anymore.
`
arma3-unix-launcher --purge`

**Comment by luca-ha** [comment]
The directory doesn't exist, I've unsubscribed and re-subscribed, but I don't see any activity.
I've rebuilt the launcher, but the weird names are still present (see picture). I guess something went wrong when I installed Arma and some files got corrupt. 
![Screenshot of the names](https://user-images.githubusercontent.com/43295692/50728445-3101a200-112a-11e9-8706-e414a0832a67.png)
Thank you very much for your work !!

**Comment by muttleyxd** [comment]
> The directory doesn't exist, I've unsubscribed and re-subscribed, but I don't see any activity.
I'm not sure if I can do anything about it, can you check if there's any thing 'rhsusaf' related in your workshop folder? These command will do:
```
find /media/lucah/Games/SteamLibrary/steamapps/workshop/content/107410 -name "rhsusaf*"
```
Please tell me, if second command gives any output, for me it displays one bikey file and a lot of bisign files.

If it doesn't display anything, then I cannot do anything about it :(

>I've rebuilt the launcher, but the weird names are still present (see picture).

It seems I didn't fix all of it, on my way :)

>Thank you very much for your work !!

Happy to do it, learning a lot while doing it :smile:

**Comment by luca-ha** [comment]
I've run the two commands, there's no such in files in both directories. I guess Steam doesn't download the mods for some reason. I'll see if I'm the only one having this issue online. Or I'll just download the files manually.
In case you want to test your fix on my weird set-up, just tell me, I'd be glad to help :smiley: .

**Comment by muttleyxd** [comment]
Closed as stale, feel free to reopen if issue persists.
